version: '3'

services:
  telligent.tag.webapi:
    build:
      context: ../../../
      dockerfile: ./src/applications/Telligent.Tag.WebApi/Dockerfile    
    image: telligent.tag.webapi
    container_name: telligent.tag.webapi
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 3030:3030
    networks:
      - telligent-network

networks:
  telligent-network:
    external: true